### PR TITLE
[Gear] Fix Master Duelist's Chit trinket

### LINKED ISSUE #5930: Trinket "Master Duelist's Chit" not simming
The Trinket [Master Duelist's Chit ](https://www.wowhead.com/item=175730/master-duelists-chit?bonus=6707)'s proc is not being simmed and the proc is not shown as dmg

Full report https://www.raidbots.com/simbot/report/hU5dC6Psu7Nq3naQKCBvUs/simc
Here is an exaple of Details! image
Simc string https://pastebin.com/GMEUmiXw

### PR DESCRIPTION
**Pull request by ThatLing**
First SimC commit, fixes the Master Duelist's Chit trinket: https://www.wowhead.com/item=175730/master-duelists-chit / https://www.wowhead.com/item=181358/master-duelists-chit.

The trinket uses spell [Dueling Form #336219](https://www.wowhead.com/spell=336219/dueling-form), which doesn't seem to be doing much? [Dueling Form #336236](https://www.wowhead.com/spell=336236/dueling-form) appears to be calling [the spell that deals damage](https://www.wowhead.com/spell=336234/duelists-shot). In Details, the spell [Duelist's Strike](https://www.wowhead.com/spell=336222/duelists-strike) is displayed (at least for melee classes), not sure why.

I added a special effect to use the correct spell, let me know if there is a better way to do this.

Fixes #5930

### CODE REVIEW

File: engine/player/unique_gear_shadowlands.cpp [hunk 1]
```diff
@@ -1984,6 +1984,24 @@ void murmurs_in_the_dark( special_effect_t& effect )
...
 
+// id=336219 driver
+// id=336236 unknown use, triggered by driver
+// id=336234 damage spell
+// id=336222 melee damage spell?
+void dueling_form( special_effect_t& effect )
+{
+  struct dueling_form_t : public generic_proc_t
+  {
+    dueling_form_t( const special_effect_t& e ) : generic_proc_t( e, "dueling_form", 336236 )
```
Comment (vituscze) [inline engine/player/unique_gear_shadowlands.cpp]: Generally, you want to use the spell id of the damage spell here, so that simc correctly picks up spell attributes, spell school, etc

File: engine/player/unique_gear_shadowlands.cpp [hunk 2]
```diff
@@ -1984,6 +1984,24 @@ void murmurs_in_the_dark( special_effect_t& effect )
   new dbc_proc_callback_t( effect.player, effect );
 }
 
+// id=336219 driver
+// id=336236 unknown use, triggered by driver
+// id=336234 damage spell
+// id=336222 melee damage spell?
+void dueling_form( special_effect_t& effect )
+{
+  struct dueling_form_t : public generic_proc_t
```
Comment (vituscze) [inline engine/player/unique_gear_shadowlands.cpp]: I believe the standard practice (for shadowlands items at least) is to use `proc_spell_t` base here.

**Review by vituscze — CHANGES_REQUESTED** [review]

File: engine/player/unique_gear_shadowlands.cpp (hunk 1 above)
Comment (ThatLing) [reply engine/player/unique_gear_shadowlands.cpp]: Wowhead says [Dueling Form #336236](https://www.wowhead.com/spell=336236/dueling-form) uses [Duelist's Shot](https://www.wowhead.com/spell=336234/duelists-shot), however Details seems to display [Duelist's Strike](https://www.wowhead.com/spell=336222/duelists-strike). How do I figure out which one to pick?

File: engine/player/unique_gear_shadowlands.cpp (hunk 2 above)
Comment (ThatLing) [reply engine/player/unique_gear_shadowlands.cpp]: Updated

File: engine/player/unique_gear_shadowlands.cpp (hunk 1 above)
Comment (vituscze) [reply engine/player/unique_gear_shadowlands.cpp]: Trust the in-game spell id. If you want to be extra sure (in case Details is doing something weird), you can check the spell id in logs produced by `/combatlog`. In-game combat log is also usable if you have some addon that lets you grab ids from spell links (such as idTip).

File: dbc_extract3/dbc/generator.py [hunk 3]
```diff
@@ -1310,6 +1310,8 @@ class SpellDataGenerator(DataGenerator):
          356305,
          # Shredded Soul (Ebonsoul Vise)
          357785,
+		 # Dueling Form (Master Duelist's Chit)
+		 336236,
```
Comment (Dorovon) [inline dbc_extract3/dbc/generator.py]:
```suggestion
         357785,
         # Dueling Form (Master Duelist's Chit)
         336236,
```
The simc code style uses spaces for indentation instead of tabs.

File: engine/player/unique_gear_shadowlands.cpp (hunk 1 above)
Comment (ThatLing) [reply engine/player/unique_gear_shadowlands.cpp]: After some digging I found [a log](https://www.warcraftlogs.com/reports/3Pg2JLzp6Qq9jnXm#fight=3&type=damage-done&source=21&view=events) that uses the trinket. The spell ID is [Duelist's Shot](https://www.wowhead.com/spell=336234/duelists-shot), so I guess it's correct like this.

**Comment by ThatLing** [comment]
I'm guessing the CI is dying because the generated DBC data isn't updated yet. I saw another PR that didn't update it so I wasn't sure. Let me know if I should include the changes.

File: engine/player/unique_gear_shadowlands.cpp (hunk 1 above)
Comment (Dorovon) [reply engine/player/unique_gear_shadowlands.cpp]: Good find, although you should still use 336234 instead of 336236 for the damage spell. Using the exact same spell ID that shows up in a combat log is important for many reasons. A few of the more visible issues that would come up with 336236 would be that the travel time of the projectile would be instant and the tooltip information will be missing in the HTML report.

I also suppose it's possible that this trinket has two separate procs, one for melee and one for ranged, but since they do the same damage I don't think it should matter much which is used. The only difference between Duelist's Strike (id=336222) and Duelist's Shot (id=336234) are the range and velocity fields.

**Comment by vituscze** [comment]
We'll regenerate the spell data once this PR is merged, so just leave it as is.

File: engine/player/unique_gear_shadowlands.cpp (hunk 1 above)
Comment (ThatLing) [reply engine/player/unique_gear_shadowlands.cpp]: Changed the spell ID to 336234
